on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/checkout@v2
      - run: sudo apt-get install mandoc
      - run: make all
      - uses: actions/upload-artifact@v2
        with:
          name: make-all
          path: build

  create_release:
    runs-on: ubuntu-latest
    needs: build
    if: contains(github.ref, 'refs/tags/v')
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: false
          prerelease: false

  release_darwin_amd64:
    runs-on: ubuntu-latest
    needs: create_release
    steps:
      - uses: actions/setup-go@v2
        with:
          go-version: ^1.15
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@v2
        with:
          name: make-all
          path: make-all
      - run: mkdir build
      - run: cp make-all/*.1 build
      - run: GOOS=darwin GOARCH=amd64 make build/fakegit
      - run: zip --no-dir-entries build.zip build/*
      - uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./build.zip
          asset_name: fakegit_darwin_amd64.zip
          asset_content_type: application/zip
